### ISSUE TITLE
SEQ Logging

### ISSUE THREAD

**Issue by ThomasJaeger** [burakoner/Bybit.Api#3]
Looks like a really well done API for Bybit.  Thank you for doing this!

One question I had was if you would recommend a best way to use SEQ logging (extension for Serilog) instead of the built in one in your API.  I didn't see a way to pass in an ILogging compatible mechanism for

```
var ws = new BybitStreamClient(new BybitStreamClientOptions
{
    RawResponse = true,
});

```

Perhaps provide a way to pass the logger with the options?

I see you have a parameter for the REST API but the logger is not assigned or used:

`public BybitRestApiClient(ILogger logger, BybitRestApiClientOptions options)`

Thank you!

**Comment by burakoner** [comment]
Yes you can pass your logger object as you describe. What's problem?
