### ISSUE TITLE
LinearInverseInstrument küçük bir bug

### ISSUE THREAD

**Issue by bymulker** [burakoner/Bybit.Api#4]
merhaba 

`[JsonConverter(typeof(LabelConverter<BybitCategory>))]
public BybitInstrumentStatus Status { get; set; }` 

->

`[JsonConverter(typeof(LabelConverter<BybitInstrumentStatus >))]
public BybitInstrumentStatus Status { get; set; }`

**Comment by burakoner** [comment]
Yeni versiyonda düzelttim. Birkaç dakika sonra yayınlıyorum. Teşekkürler
