### ISSUE TITLE
Mismatch data type in instrument description model

### ISSUE THREAD

**Issue by dnmsk** [burakoner/Bybit.Api#5]
[BybitSpotInstrumentLotSizeFilter](https://github.com/burakoner/Bybit.Api/blob/1284d7e4796d553838166f462c4f8f2b4faad401/Bybit.Api/Models/Market/BybitInstrument.cs#L29C1-L30C44)

There is unclear description in market Bybit api for instrument type, but in response example it is decimal for spot.

https://bybit-exchange.github.io/docs/v5/market/instrument#response-parameters
```
>> basePrecision	string	The precision of base coin
>> quotePrecision	string	The precision of quote coin
```

https://bybit-exchange.github.io/docs/spot/public/instrument#response-parameters
```
> basePrecision	string	Decimal precision (base currency)
> quotePrecision	string	Decimal precision (quote currency)
```

**Comment by burakoner** [comment]
Fixed in new version. Thank you very much
